name: loadBalancer001
on: 
  workflow_dispatch:
    inputs:
      servername:
        description: "Enter Server name"
        required: true
        type: string

jobs:
  fast1:
    name: "Remove server001"
    runs-on: self-hosted
    
    env:
      server_name: ${{ github.event.inputs.servername }}
      first_three_characters: ${{ server_name:0:3 }}
      middle_three_characters: ${{ server_name:4:3 }}

    steps:
      - name: "check condition"
        if: ${{ github.event.inputs.servername == 'AWSVPSFASTF91' }}
        run: |
          echo "$server_name is valid"
          echo "First three characters: $first_three_characters"
          echo "Middle three characters: $middle_three_characters"
           
      - name: "Validating condition"
        run: | 
          echo "**** Printing 2nd time for validation *****"
          echo "First three characters: $first_three_characters"
          echo "Middle three characters: $middle_three_characters"
          echo "Server name: $server_name"
