# Content of template.yaml
name: Template20feb
on:
  workflow_call:
    inputs:
      target_group:
        required: true
        type: string
      azure_id:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
jobs:
  print_variables:
    runs-on: self-hosted
    steps:
      - name: Print Variables
        run: |
          echo "Target Group: ${{ inputs.target_group }}"
          echo "Azure ID: ${{ inputs.azure_id }}"
          echo "AWS Account ID: ${{ inputs.aws_account_id }}"
