name: loadBalancer-test001
on: 
  workflow_dispatch:
    inputs:
      servername:
        description: "Enter Server name"
        required: true
        type: string

jobs:
  fast1:
    name: "Remove server-test001"
    runs-on: self-hosted
    steps:
      - name: "Check condition and split value"
        if: ${{ github.event.inputs.servername == 'AWSVPIISFASTF91' }}
        env:
          server_name: ${{ github.event.inputs.servername }}
        run: |
          # Extracting variables
          cloud_name="${server_name:0:3}"
          server_type="${server_name:3:2}"
          server_name_part="${server_name:5:3}"
          env_name="${server_name:8:4}"
          end_file="${server_name:(-3)}"
          
          # Printing variables
          echo "Cloud Name: $cloud_name"
          echo "Server Type: $server_type"
          echo "Server Name: $server_name_part"
          echo "Environment Name: $env_name"
          echo "End File: $end_file"
          
          # Switch statement based on server_type
          case $server_type in
            vn)
              echo "Switch-case--> Server Type is vn"
              ;;
            vp)
              echo "Switch-case--> Server Type is vp"
              ;;
            *)
              echo "Unknown server type in Switch-case"
              ;;
          esac
